#mongohost: ds061371.mongolab.com
#mongoport: 61371
mongodb: playciv

#mongouri: mongodb://uedpt8zicq3wq9pmufbb:Sl73pBNcaQvy4rhLEAjx@bsgmvikhtnhzjez-mongodb.services.clever-cloud.com:27017/bsgmvikhtnhzjez
#mongodb://<username>:<password>@playciv-shard-00-00.4cayc.mongodb.net:27017,playciv-shard-00-01.4cayc.mongodb.net:27017,playciv-shard-00-02.4cayc.mongodb.net:27017/heroku_app35355040?ssl=true&replicaSet=atlas-13uywy-shard-0&authSource=admin&retryWrites=true&w=majority


#Application config
server:
  #applicationConnectors:
    #type: https
    #port: 8443
    #Look at http://www.chrissearle.org/2007/10/25/Adding_self-signed_https_certificates_to_java_keystore/
  type: simple
  rootPath: '/api/*'
  applicationContextPath: /
  adminContextPath: /admin
  gzip:
    enabled: true
    bufferSize: 8KiB

  connector:
    type: http
    port: 8080

  requestLog:
    timeZone: Europe/Oslo

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'no.asgari.civilization' to DEBUG.
    no.asgari.civilization: DEBUG
    #org.eclipse.jetty.servlets: DEBUG

  appenders:
    - type: console
      timeZone: Europe/Oslo
#authenticationCachePolicy: maximumSize=100, expireAfterAccess=10m